services:
  instagram-collector:
    build: .
    environment:
      - API_BASE_URL=${API_BASE_URL}
      - SECRET_TOKEN=${SECRET_TOKEN}
    command: sh -c "timeout 15m python3 main.py"
    restart: "no"